
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # the app listens on 8080; publish it
    ports:
      - "4000:8080"
    # environment:
      # JAVA_OPTS: "-Dserver.port=9191"
    # ensure your ENTRYPOINT uses JAVA_OPTS if you set it:
    # ENTRYPOINT ["sh","-lc","exec java $JAVA_OPTS -jar /app/app.jar"]

  prometheus:
    image: prom/prometheus:latest
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
