name: Terraform CI

on:
  push:
    branches: [ main ]
    paths: [ "terraform/infra/*.tf", "backend.hcl" ]
  pull_request:
    branches: [ main ]
    paths: [ "terraform/infra/*.tf", "backend.hcl" ]
  workflow_dispatch:


jobs:
  plan_apply:
    runs-on: [self-hosted]   # or [self-hosted, ec2] if you use a custom label
    defaults:
      run:
        working-directory: terraform/infra
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: terraform/infra/
          sparse-checkout-cone: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

       # Formatting guard (fails PR if files need reformatting)
      - name: Terraform Format (check)
        run: terraform fmt -check -recursive

      #  show the diff for debugging if fmt check fails
      - name: Terraform Format (diff)
        if: failure()                   # only runs if the previous step failed
        run: terraform fmt -diff -recursive

      - name: Terraform Init (S3+DDB backend)
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Apply
        run: terraform apply tfplan

      - name: Cleanup tfplan file
        if: always()                   
        run: rm -f tfplan 